# See https://www.gitpod.io/docs/config-gitpod-file.

image:
  file: gitpod/Dockerfile

tasks:
  - init: ./sh/configure.sh
    # Ensure all Python packages are installed (so that we don't have to rebuild
    # the Gitpod image every time a new small Python dependency is added).
    command: pip install -r gradient/requirements.txt

vscode:
  extensions:
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - streetsidesoftware.code-spell-checker
    - mutantdino.resourcemonitor
    - innerlee.nvidia-smi
